export type Locale = "cs" | "en";

export const copy = {
  cs: {
    brand: "Japonsko / 2027",
    homeLabel: "Japonsko 2027 — domů",
    skip: "Přejít na obsah",
    navLabel: "Hlavní navigace",
    route: "Trasa",
    itinerary: "Program",
    journal: "Deník",
    heroEyebrow: "Cesta sdílená s přáteli a rodinou",
    heroTitle: <>Japonsko<br />2027</>,
    heroIntro: "Patnáct dní mezi velkoměsty, chrámy, horami a rozkvetlými sakurami.",
    heroLink: "Prozkoumat cestu",
    introEyebrow: "Naše cesta",
    introTitle: <>Jedna země.<br />Tisíc detailů.</>,
    intro: [
      "Na jaře 2027 vyrážíme do Japonska. Tady budeme sdílet trasu, každodenní zážitky a fotografie s přáteli a rodinou.",
      "Program už máme. Příběhy a snímky začnou přibývat během cesty — deník poroste společně s ní.",
    ],
    routeEyebrow: "1.–15. dubna 2027",
    routeTitle: "Mapa cesty",
    routeNote: "Akvarelová mapa zachycuje zastávky expedice. Číslované odkazy pod ní vedou na jednotlivé dny.",
    mapAlt: "Akvarelová mapa Japonska s vyznačenými zastávkami fotografické cesty v dubnu 2027.",
    mapNav: "Dny a místa na trase",
    mapKey: "Číslované odkazy vedou přímo na podrobný program každého dne.",
    itineraryEyebrow: "Den po dni",
    itineraryNote: "Plán se může měnit podle počasí, sakur a toho, co objevíme cestou.",
    journalEyebrow: "Zápisky z cesty",
    journalNote: "První příběhy a fotografie z Japonska se tu objeví v roce 2027.",
    read: "Přečíst zápisek",
    closing: <>Cestovat pomalu.<br />Všímat si všeho.</>,
    footer: "Osobní cestovní deník.",
    back: "Zpět do deníku",
    planning: "Přípravy",
  },
  en: {
    brand: "Japan / 2027",
    homeLabel: "Japan 2027 — home",
    skip: "Skip to content",
    navLabel: "Primary navigation",
    route: "Route",
    itinerary: "Itinerary",
    journal: "Journal",
    heroEyebrow: "A journey shared with friends & family",
    heroTitle: <>Japan<br />2027</>,
    heroIntro: "Fifteen days among cities, temples, mountains, and cherry blossom.",
    heroLink: "Explore the journey",
    introEyebrow: "Our journey",
    introTitle: <>One country.<br />A thousand details.</>,
    intro: [
      "In spring 2027 we are heading to Japan. This is where we will share the route, daily experiences, and photographs with friends and family.",
      "The itinerary is ready. Stories and pictures will begin to appear during the trip — the journal will grow as we travel.",
    ],
    routeEyebrow: "1–15 April 2027",
    routeTitle: "Journey map",
    routeNote: "The watercolour map shows the expedition stops. Numbered links below it lead to each day.",
    mapAlt: "Watercolour map of Japan showing the stops on the April 2027 photography journey.",
    mapNav: "Days and places on the route",
    mapKey: "Numbered links lead directly to the detailed itinerary for each day.",
    itineraryEyebrow: "Day by day",
    itineraryNote: "Plans may change with the weather, the blossom, and what we discover along the way.",
    journalEyebrow: "Field notes",
    journalNote: "The first stories and photographs from Japan will appear here in 2027.",
    read: "Read the note",
    closing: <>Travel slowly.<br />Notice everything.</>,
    footer: "A personal travel journal.",
    back: "Back to the journal",
    planning: "Planning",
  },
} as const;

export const mapStops = [
  { id: "day-1", number: "01", cs: "Praha", en: "Prague" },
  { id: "day-2", number: "02", cs: "Tokio", en: "Tokyo" },
  { id: "day-3", number: "03", cs: "Hirošima", en: "Hiroshima" },
  { id: "day-4", number: "04", cs: "Mijadžima", en: "Miyajima" },
  { id: "day-5", number: "05", cs: "Ósaka", en: "Osaka" },
  { id: "day-6-8", number: "06–08", cs: "Kjóto", en: "Kyoto" },
  { id: "day-9", number: "09", cs: "Nara", en: "Nara" },
  { id: "day-10", number: "10", cs: "Jošino", en: "Yoshino" },
  { id: "day-11", number: "11", cs: "Kanazawa", en: "Kanazawa" },
  { id: "day-12", number: "12", cs: "Nagano / Tokio", en: "Nagano / Tokyo" },
  { id: "day-13", number: "13", cs: "Fudži", en: "Fuji" },
  { id: "day-14", number: "14", cs: "Tokio", en: "Tokyo" },
  { id: "day-15", number: "15", cs: "Návrat", en: "Return" },
] as const;

export const itinerary = [
  { id: "day-1", number: "01", date: "2027-04-01", csDate: "1. 4. 2027", enDate: "1 April 2027", csTitle: "Odlet z Prahy", enTitle: "Departure from Prague", csText: "Naše cesta začíná odletem z Prahy.", enText: "Our journey begins with a flight from Prague." },
  { id: "day-2", number: "02", date: "2027-04-02", csDate: "2. 4. 2027", enDate: "2 April 2027", csTitle: "Cesta do Japonska", enTitle: "Journey to Japan", csText: "S přestupem v Koreji doletíme do Tokia a po dlouhé cestě si odpočineme.", enText: "After a connection in Korea, we will arrive in Tokyo and rest after the long journey." },
  { id: "day-3", number: "03", date: "2027-04-03", csDate: "3. 4. 2027", enDate: "3 April 2027", csTitle: "Hirošima", enTitle: "Hiroshima", csText: "Hirošima byla jedním ze dvou míst zasažených jaderným bombardováním za druhé světové války. Odpoledne navštívíme místní zahrady a mírový památník s muzeem. Večer budeme fotografovat u slavného A-Bomb Dome, jediné zachovalé ruiny připomínající zkázu města.", enText: "Hiroshima was one of the two cities struck by an atomic bomb during the Second World War. In the afternoon we will visit its gardens, Peace Memorial, and museum. In the evening we will photograph the famous A-Bomb Dome, the preserved ruin that recalls the destruction of the city." },
  { id: "day-4", number: "04", date: "2027-04-04", csDate: "4. 4. 2027", enDate: "4 April 2027", csTitle: "Mijadžima", enTitle: "Miyajima", csText: "Posvátný ostrov nabízí nádherný chrám, výhled z hory Misen na okolní ostrovy a torii, která patří k symbolům Japonska. Budeme zde fotografovat také jeleny a hluboký les.", enText: "The sacred island offers a beautiful shrine, a view across the surrounding islands from Mount Misen, and the torii that is one of Japan’s symbols. We will also photograph deer and the deep forest." },
  { id: "day-5", number: "05", date: "2027-04-05", csDate: "5. 4. 2027", enDate: "5 April 2027", csTitle: "Ósaka", enTitle: "Osaka", csText: "Rychlovlakem přejedeme do Ósaky, kde nás čekají plovoucí zahrady a kvetoucí sakury. Program ve městě přizpůsobíme místům, kde budou právě v nejlepším květu.", enText: "We will take the bullet train to Osaka for the Floating Garden and cherry blossom. Our plans in the city will follow wherever the sakura are at their best." },
  { id: "day-6-8", number: "06–08", date: "2027-04-06", csDate: "6.–8. 4. 2027", enDate: "6–8 April 2027", csTitle: "Kjóto", enTitle: "Kyoto", csText: "Kjóto je historické město obklopené zelení. Navštívíme Zlatý pavilon ze 14. století v japonské zahradě, chrám Heian Jingu, dřevěné terasy Kiyomizudera při západu slunce a horu Daimonji. Čeká nás také historická čtvrť Higašijama, bambusový les, Arašijama a další místa.", enText: "Kyoto is a historic city surrounded by greenery. We will visit the fourteenth-century Golden Pavilion in its Japanese garden, Heian Jingu, the wooden terraces of Kiyomizudera at sunset, and Mount Daimonji. The historic Higashiyama district, bamboo grove, Arashiyama, and more are also on our route." },
  { id: "day-9", number: "09", date: "2027-04-09", csDate: "9. 4. 2027", enDate: "9 April 2027", csTitle: "Nara", enTitle: "Nara", csText: "Dopoledne navštívíme město Nara, známé památkami z 8. století. Kromě chrámu Tódaidži uvidíme místní zahrady a čtvrť Naramachi — Japonsko tak, jak si ho představujeme z knih o samurajích.", enText: "In the morning we will visit Nara, known for its eighth-century monuments. Alongside Tōdai-ji Temple, we will see local gardens and the Naramachi district — the Japan we imagine from books about samurai." },
  { id: "day-10", number: "10", date: "2027-04-10", csDate: "10. 4. 2027", enDate: "10 April 2027", csTitle: "Jošino", enTitle: "Yoshino", csText: "Vyrazíme na celodenní výlet do Jošina, které je známé největší koncentrací sakur v Japonsku. Toto kouzelné místo budeme fotografovat z několika vyhlídek.", enText: "We will spend the day in Yoshino, known for the greatest concentration of cherry trees in Japan, and photograph this remarkable place from several viewpoints." },
  { id: "day-11", number: "11", date: "2027-04-11", csDate: "11. 4. 2027", enDate: "11 April 2027", csTitle: "Kanazawa", enTitle: "Kanazawa", csText: "Celý den strávíme v Kanazawě. Město je známé jedněmi z nejkrásnějších zahrad v Japonsku, historickým hradem a čtvrtí Nagamachi Samurai District, která bývala sídlem samurajů.", enText: "We will spend the whole day in Kanazawa. The city is known for some of Japan’s most beautiful gardens, its historic castle, and Nagamachi Samurai District, once home to samurai families." },
  { id: "day-12", number: "12", date: "2027-04-12", csDate: "12. 4. 2027", enDate: "12 April 2027", csTitle: "Nagano / Tokio", enTitle: "Nagano / Tokyo", csText: "Podle situace se sakurami vyrazíme buď do Nagana, nebo do Tokia, abychom zvýšili šanci na co nejkrásnější fotografie rozkvetlých stromů.", enText: "Depending on the cherry blossom, we will travel either to Nagano or Tokyo to give ourselves the best chance of photographing the trees in full bloom." },
  { id: "day-13", number: "13", date: "2027-04-13", csDate: "13. 4. 2027", enDate: "13 April 2027", csTitle: "Hora Fudži", enTitle: "Mount Fuji", csText: "Hora Fudži je dalším symbolem Japonska. Podle počasí máme připravené tři varianty fotografických míst: jezero Aši, Šimo-Jošida nebo jezero Kawaguči.", enText: "Mount Fuji is another symbol of Japan. Depending on the weather, we have three possible photography locations: Lake Ashi, Shimoyoshida, or Lake Kawaguchi." },
  { id: "day-14", number: "14", date: "2027-04-14", csDate: "14. 4. 2027", enDate: "14 April 2027", csTitle: "Tokio", enTitle: "Tokyo", csText: "Poslední den věnujeme hlavnímu městu. Budeme fotografovat v historických čtvrtích, zahradách a císařském areálu i v moderních čtvrtích, jako je Ginza.", enText: "Our last day belongs to Japan’s capital. We will photograph historic districts, gardens, and the imperial grounds as well as modern neighbourhoods such as Ginza." },
  { id: "day-15", number: "15", date: "2027-04-15", csDate: "15. 4. 2027", enDate: "15 April 2027", csTitle: "Cesta zpět do ČR", enTitle: "Journey home", csText: "Loučíme se s Japonskem a vyrážíme na cestu domů.", enText: "We say goodbye to Japan and begin the journey back to the Czech Republic." },
] as const;
